name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set env
        run: php scripts/deploy_set_env.php
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

      - name: Package
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.PACKAGE_LIST }}
          dest: package.zip
          recursive: false

      - name: Upload to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          localPath: package.zip
          remotePath: ${{ secrets.DEPLOY_PATH }}/package.zip

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            rm -rf ${{ env.REMOVE_LIST }}
            unzip -o ${{ secrets.DEPLOY_PATH }}/package.zip -d ${{ secrets.DEPLOY_PATH }}
            rm -rf ${{ secrets.DEPLOY_PATH }}/package.zip
